In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, Normalizer
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error

# **Tennis**

In [ ]:
df = pd.read_csv('/content/play_tennis.csv')

In [ ]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [ ]:
df.describe()

       day outlook  temp humidity  wind play
count   14      14    14       14    14   14
unique  14       3     3        2     2    2
top     D1   Sunny  Mild     High  Weak  Yes
freq     1       5     6        7     8    9

In [ ]:
df.isnull().sum()

day         0
outlook     0
temp        0
humidity    0
wind        0
play        0
dtype: int64

In [ ]:
label_encoder = LabelEncoder() 
df['outlook'] = label_encoder.fit_transform(df['outlook'])
df['temp']= label_encoder.fit_transform(df['temp'])
df['humidity']= label_encoder.fit_transform(df['humidity'])
df['wind']= label_encoder.fit_transform(df['wind'])
df['play']= label_encoder.fit_transform(df['play'])

In [ ]:
df.drop(['day'], axis=1, inplace=True)

In [ ]:
df.head()

   outlook  temp  humidity  wind  play
0        2     1         0     1     0
1        2     1         0     0     0
2        0     1         0     1     1
3        1     2         0     1     1
4        1     0         1     1     1

In [ ]:
y = df['play']
x = df.drop(['play'],axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [ ]:
model = GaussianNB()

In [ ]:
model.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
df_pred=pd.DataFrame()

In [ ]:
df_pred['y_test']=y_test
df_pred['y_pred']=y_pred

In [ ]:
print(df_pred)

   y_test  y_pred
3       1       1
7       0       1
6       1       1

In [ ]:
if model.predict([[2,0,0,1]])==0:
  print("No")
else:
  print("Yes")

No

In [ ]:
print(accuracy_score(y_test,y_pred))

0.6666666666666666

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[0 1]
 [0 2]]

# **Titanic**

In [ ]:
df2 = pd.read_csv('/content/tested.csv')

In [ ]:
df2.head()

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0          892         0       3  ...   7.8292   NaN         Q
1          893         1       3  ...   7.0000   NaN         S
2          894         0       2  ...   9.6875   NaN         Q
3          895         0       3  ...   8.6625   NaN         S
4          896         1       3  ...  12.2875   NaN         S

[5 rows x 12 columns]

In [ ]:
df2.drop(['Name'], axis=1, inplace=True)
df2.drop(['Ticket'], axis=1, inplace=True)
df2.drop(['Cabin'], axis=1, inplace=True)
df2.drop(['PassengerId'], axis=1, inplace=True)

In [ ]:
df2.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [ ]:
df2.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [ ]:
df2.describe

<bound method NDFrame.describe of      Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
413         0       3    male   NaN      0      0    8.0500        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S
416         0       3    male   NaN      0      0    8.0500        S
417         0       3    male   NaN      1      1   22.3583        C

[418 rows x 8 columns]>

In [ ]:
df2 = df2.dropna()

In [ ]:
df2.describe

<bound method NDFrame.describe of      Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0           0       3    male  34.5      0      0    7.8292        Q
1           1       3  female  47.0      1      0    7.0000        S
2           0       2    male  62.0      0      0    9.6875        Q
3           0       3    male  27.0      0      0    8.6625        S
4           1       3  female  22.0      1      1   12.2875        S
..        ...     ...     ...   ...    ...    ...       ...      ...
409         1       3  female   3.0      1      1   13.7750        S
411         1       1  female  37.0      1      0   90.0000        Q
412         1       3  female  28.0      0      0    7.7750        S
414         1       1  female  39.0      0      0  108.9000        C
415         0       3    male  38.5      0      0    7.2500        S

[331 rows x 8 columns]>

In [ ]:
df2.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [ ]:
label_encoder = LabelEncoder() 
df2['Sex'] = label_encoder.fit_transform(df2['Sex'])
df2['Embarked']= label_encoder.fit_transform(df2['Embarked'])

In [ ]:
df2.head()

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  34.5      0      0   7.8292         1
1         1       3    0  47.0      1      0   7.0000         2
2         0       2    1  62.0      0      0   9.6875         1
3         0       3    1  27.0      0      0   8.6625         2
4         1       3    0  22.0      1      1  12.2875         2

In [ ]:
y = df2['Survived']
x = df2.drop(['Survived'],axis=1)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [ ]:
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
df2_pred=pd.DataFrame()

In [ ]:
df2_pred['y_test']=y_test
df2_pred['y_pred']=y_pred

In [ ]:
print(df_pred)

   y_test  y_pred
3       1       1
7       0       1
6       1       1

In [ ]:
if model.predict([[3,0,47.0,1,0,7.000, 2]])==0:
  print("No")
else:
  print("Yes")

Yes

In [ ]:
print(accuracy_score(y_test,y_pred))

1.0

**Conclusion:**

Successfully implemented Naïve Bayes Algorithm to predict the class of a new data point using sklearn and obtained the accuracy score.